name: CI
on:
  push:
    branches:
      - main
  workflow_call:

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - "**"
#

jobs:
  rust_check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - uses: davidB/rust-cargo-make@v1
      - uses: taiki-e/install-action@nextest

      - name: Run Clippy
        run: |
          cargo make clippy

      - name: Run Rustfmt
        run: |
          cargo make fmt

      - name: Run cargo doc
        run: cargo doc --no-deps

      - name: Spell Check
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        uses: crate-ci/typos@master

      - name: Audit
        uses: actions-rust-lang/audit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          cargo make test
      - name: Run Doc Tests
        run: |
          cargo make doc-test
